[package]
name = "bevy-bicycle"
version = "0.1.0"
edition = "2021"

[dependencies]
avian2d = { git = "https://github.com/Jondolf/avian.git", branch = "main", default-features = false, features = ["2d", "f64", "parry-f64", "debug-plugin", "enhanced-determinism"] }
bevy = { version = "0.15", features= ["wayland"] }
bevy_egui = "0.31.1"
# bevy-parallax = {git = "https://github.com/Corrosive-Games/bevy-parallax.git"}
